### ISSUE TITLE
Does not compile with Rust 1.88.0-nightly

### ISSUE THREAD

**Issue by ByteHamster** [zommiommy/common_traits#3]
When compiling with Rust 1.88.0-nightly, I get the following error message. Seems to be caused by the fact that common_traits uses glob imports.

```
error[E0659]: `Atomic` is ambiguous
 --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:5:9
  |
5 | impl<T: Atomic + AsBytes> FromBytes for T
  |         ^^^^^^ ambiguous name
  |
  = note: ambiguous because of multiple glob imports of a name in the same module
note: `Atomic` could refer to the trait imported here
 --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:1:5
  |
1 | use crate::*;
  |     ^^^^^^^^
  = help: consider adding an explicit import of `Atomic` to disambiguate
note: `Atomic` could also refer to the type alias imported here
 --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:3:5
  |
3 | use core::sync::atomic::*;
  |     ^^^^^^^^^^^^^^^^^^^^^
  = help: consider adding an explicit import of `Atomic` to disambiguate

error[E0659]: `Atomic` is ambiguous
  --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:11:28
   |
11 |         Self::new(<Self as Atomic>::NonAtomicType::from_be_bytes(bytes))
   |                            ^^^^^^ ambiguous name
   |
   = note: ambiguous because of multiple glob imports of a name in the same module
note: `Atomic` could refer to the trait imported here
  --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:1:5
   |
1  | use crate::*;
   |     ^^^^^^^^
   = help: consider adding an explicit import of `Atomic` to disambiguate
note: `Atomic` could also refer to the type alias imported here
  --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:3:5
   |
3  | use core::sync::atomic::*;
   |     ^^^^^^^^^^^^^^^^^^^^^
   = help: consider adding an explicit import of `Atomic` to disambiguate

error[E0659]: `Atomic` is ambiguous
  --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:15:28
   |
15 |         Self::new(<Self as Atomic>::NonAtomicType::from_ne_bytes(bytes))
   |                            ^^^^^^ ambiguous name
   |
   = note: ambiguous because of multiple glob imports of a name in the same module
note: `Atomic` could refer to the trait imported here
  --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:1:5
   |
1  | use crate::*;
   |     ^^^^^^^^
   = help: consider adding an explicit import of `Atomic` to disambiguate
note: `Atomic` could also refer to the type alias imported here
  --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:3:5
   |
3  | use core::sync::atomic::*;
   |     ^^^^^^^^^^^^^^^^^^^^^
   = help: consider adding an explicit import of `Atomic` to disambiguate

error[E0659]: `Atomic` is ambiguous
  --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:19:28
   |
19 |         Self::new(<Self as Atomic>::NonAtomicType::from_le_bytes(bytes))
   |                            ^^^^^^ ambiguous name
   |
   = note: ambiguous because of multiple glob imports of a name in the same module
note: `Atomic` could refer to the trait imported here
  --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:1:5
   |
1  | use crate::*;
   |     ^^^^^^^^
   = help: consider adding an explicit import of `Atomic` to disambiguate
note: `Atomic` could also refer to the type alias imported here
  --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:3:5
   |
3  | use core::sync::atomic::*;
   |     ^^^^^^^^^^^^^^^^^^^^^
   = help: consider adding an explicit import of `Atomic` to disambiguate

error[E0659]: `Atomic` is ambiguous
   --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:172:14
    |
172 |         impl Atomic for $aty {
    |              ^^^^^^ ambiguous name
    |
    = note: ambiguous because of multiple glob imports of a name in the same module
note: `Atomic` could refer to the trait imported here
   --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:1:5
    |
1   | use crate::*;
    |     ^^^^^^^^
    = help: consider adding an explicit import of `Atomic` to disambiguate
note: `Atomic` could also refer to the type alias imported here
   --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:3:5
    |
3   | use core::sync::atomic::*;
    |     ^^^^^^^^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `Atomic` to disambiguate

error[E0659]: `Atomic` is ambiguous
   --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:891:6
    |
891 | impl Atomic for AtomicBool {
    |      ^^^^^^ ambiguous name
    |
    = note: ambiguous because of multiple glob imports of a name in the same module
note: `Atomic` could refer to the trait imported here
   --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:1:5
    |
1   | use crate::*;
    |     ^^^^^^^^
    = help: consider adding an explicit import of `Atomic` to disambiguate
note: `Atomic` could also refer to the type alias imported here
   --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:3:5
    |
3   | use core::sync::atomic::*;
    |     ^^^^^^^^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `Atomic` to disambiguate

error[E0659]: `Atomic` is ambiguous
    --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:1427:36
     |
1427 |                 Self::new(<Self as Atomic>::NonAtomicType::ZERO)
     |                                    ^^^^^^ ambiguous name
     |
     = note: ambiguous because of multiple glob imports of a name in the same module
note: `Atomic` could refer to the trait imported here
    --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:1:5
     |
1    | use crate::*;
     |     ^^^^^^^^
     = help: consider adding an explicit import of `Atomic` to disambiguate
note: `Atomic` could also refer to the type alias imported here
    --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:3:5
     |
3    | use core::sync::atomic::*;
     |     ^^^^^^^^^^^^^^^^^^^^^
     = help: consider adding an explicit import of `Atomic` to disambiguate

error[E0659]: `Atomic` is ambiguous
    --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:1506:14
     |
1506 |         impl Atomic for $aty {
     |              ^^^^^^ ambiguous name
     |
     = note: ambiguous because of multiple glob imports of a name in the same module
note: `Atomic` could refer to the trait imported here
    --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:1:5
     |
1    | use crate::*;
     |     ^^^^^^^^
     = help: consider adding an explicit import of `Atomic` to disambiguate
note: `Atomic` could also refer to the type alias imported here
    --> /home/bytehamster/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/common_traits-0.11.2/src/impls.rs:3:5
     |
3    | use core::sync::atomic::*;
     |     ^^^^^^^^^^^^^^^^^^^^^
     = help: consider adding an explicit import of `Atomic` to disambiguate

```

**Comment by zommiommy** [comment]
Thank you, I'll fix it and publish a new version asap

**Comment by vigna** [comment]
In retrospect, the guidelines should require to always try and compile with +nightly, too.

**Comment by zommiommy** [comment]
@ByteHamster can you try the latest commit before I publish the new version?
I've tried to reproduce it and I don't get that error.

![Image](https://github.com/user-attachments/assets/f9b98eec-c519-468f-b3af-611780f0f095)

**Comment by ByteHamster** [comment]
> In retrospect, the guidelines should require to always try and compile with +nightly, too.

It only breaks in recent nightlies and did work a few weeks ago in nightly. Rust rolling out breaking changes every couple of weeks is getting a bit annoying... Had that several times already 

> can you try the latest commit before I publish the new version?

I think it works. I can't properly test a full build because when I delete the lock file (to patch common_traits to the most recent version), some other dependency updates to a version with breaking changes. However, with your most recent commit, the build no longer fails when building common_traits but fails later, so I guess your part is fixed.

**Comment by vigna** [comment]
> > In retrospect, the guidelines should require to always try and compile with +nightly, too.
> 
> It only breaks in recent nightlies and did work a few weeks ago in nightly. Rust rolling out breaking changes every couple of weeks is getting a bit annoying... Had that several times already 
> 

Stupid question maybe but... Why nightly? We don't touch it, not even with a ten-foot pole.

**Comment by ByteHamster** [comment]
Because some other dependency I had in my project depended on a nightly feature

**Comment by vigna** [comment]
Well then you have to. 

I'm puzzled because in the past when something like that could happen we would be alerted before the release. They compile all of crates.io.

**Comment by ByteHamster** [comment]
I don't know. To be honest, I don't know anything about Rust and just try to ensure that my competitors keep compiling

**Comment by workingjubilee** [comment]
We should probably lint on multiple glob imports.

**Comment by zommiommy** [comment]
Yeah, I'll probably add a ['#[deny(pedantic::wildcard_imports)]'](https://rust-lang.github.io/rust-clippy/master/index.html#/glob)
